name: miscellaneous_app
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.1.1 <4.0.0'

dependencies:
  dio: ^5.3.3
  flutter:
    sdk: flutter
  flutter_compass: ^0.8.0
  flutter_riverpod: ^2.4.4
  go_router: ^11.1.4
  google_fonts: ^6.1.0
  permission_handler: ^11.0.1
  sensors_plus: ^3.1.0
  share_plus: ^7.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/